// Code generated by MockGen. DO NOT EDIT.
// Source: messageInteractor.go

// Package interactor is a generated GoMock package.
package interactor

import (
	model "github.com/MegaBlackLabel/go-clean-architecture-testing-practice/domain/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockMessageInteractor is a mock of MessageInteractor interface
type MockMessageInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockMessageInteractorMockRecorder
}

// MockMessageInteractorMockRecorder is the mock recorder for MockMessageInteractor
type MockMessageInteractorMockRecorder struct {
	mock *MockMessageInteractor
}

// NewMockMessageInteractor creates a new mock instance
func NewMockMessageInteractor(ctrl *gomock.Controller) *MockMessageInteractor {
	mock := &MockMessageInteractor{ctrl: ctrl}
	mock.recorder = &MockMessageInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMessageInteractor) EXPECT() *MockMessageInteractorMockRecorder {
	return m.recorder
}

// Publish mocks base method
func (m *MockMessageInteractor) Publish(message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish
func (mr *MockMessageInteractorMockRecorder) Publish(message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockMessageInteractor)(nil).Publish), message)
}

// Subscribe mocks base method
func (m *MockMessageInteractor) Subscribe(callback model.Callback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe
func (mr *MockMessageInteractorMockRecorder) Subscribe(callback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockMessageInteractor)(nil).Subscribe), callback)
}
